name: MySQL Schema Update

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC (adjust for IST if needed)
  push:
    branches:
      - main

jobs:
  update-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MySQL
        uses: mirkokiefer/mysql-action@v1.1
        with:
          mysql database: 'your_database'
          mysql user: 'your_user'
          mysql password: '${{ secrets.DB_PASSWORD }}'

      - name: Apply schema updates
        run: |
          mysql -u your_user -p${{ secrets.DB_PASSWORD }} your_database < schema.sql

      - name: Set up GPG signing
        run: |
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgsign true

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -S -m 'Automated schema update'
          git push
